CREATE OR REPLACE VIEW client_projects AS
    SELECT P.PROJECT_TITLE, P.DATE_STARTED, P.DATE_ENDED, C.CLIENT_NAME
    FROM PROJECT P
    JOIN CLIENT C
    ON P.CLIENT_ID = C.ID
    WHERE P.CLIENT_ID = 5;