insert into employee_role (id, role) values (1,'Development Manager');
insert into employee_role (id, role) values (2,'Testing Manager');
insert into employee_role (id, role) values (3,'Software Developer');
insert into employee_role (id, role) values (4,'Technical Architect');
insert into employee_role (id, role) values (5,'Solutions Architect');
insert into employee_role (id, role) values (6,'Enterprise Architect');
insert into employee_role (id, role) values (7,'Data Architect');
insert into employee_role (id, role) values (8,'Integration Architect');
insert into employee_role (id, role) values (9,'Systems Architect');
insert into employee_role (id, role) values (10,'Infrastructure Architect');
insert into employee_role (id, role) values (11,'Operations Architect');
insert into employee_role (id, role) values (12,'Frontend Architect');
insert into employee_role (id, role) values (13,'Build Engineer');
insert into employee_role (id, role) values (14,'Java Developer');
insert into employee_role (id, role) values (15,'Full Stack Developer');
insert into employee_role (id, role) values (16,'Frontend Developer');
insert into employee_role (id, role) values (17,'Team Lead');
insert into employee_role (id, role) values (18,'Operations Engineer');
insert into employee_role (id, role) values (19,'Systems Administrator');
insert into employee_role (id, role) values (20,'Linux Engineer');
insert into employee_role (id, role) values (21,'DevOps Engineer');
insert into employee_role (id, role) values (22,'Database Administrator');
insert into employee_role (id, role) values (23,'Test Engineer');
insert into employee_role (id, role) values (24,'QA');
insert into employee_role (id, role) values (25,'Test Automation Engineer');
insert into employee_role (id, role) values (26,'SDET');
insert into employee_role (id, role) values (27,'Developer In Test');
insert into employee_role (id, role) values (28,'Tech Tester');
insert into employee_role (id, role) values (29,'Business Analyst');
insert into employee_role (id, role) values (30,'Product Owner');
insert into employee_role (id, role) values (31,'Scrum Master');
insert into employee_role (id, role) values (32,'Support Analyst');